language: node_js
node_js: stable

# assign build branches
branches:
  only:
    - source

# cache this directory
cache:
  directories:
    - node_modules

# S: Build Lifecycle
before_install:
  - openssl aes-256-cbc -K $encrypted_58422cf2da09_key -iv $encrypted_58422cf2da09_iv -in ./travis/id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp travis/ssh_config ~/.ssh/config
  - npm install -g hexo-cli 
  - git clone -b mod https://github.com/jqyisbest/CustomThemeForMyBlog.git themes/next

install:
  - npm install

script:
  - hexo generate

after_success:
  - git config --global user.name "JQYisBest"
  - git config --global user.email "JQYisBest@foxmail.com"
  - sed -i'' "/^ *repo/s~github\.com~${githubToken}@github.com~" _config.yml
  - hexo deploy
# E: Build LifeCycle